// ============================================================
// الملف المركزي لجميع نصوص الواجهة (UI Strings)
// ------------------------------------------------------------
// عدّل أي نص هنا وسيظهر التعديل في كل مكان يستخدم النص.
// النصوص الديناميكية مكتوبة كدوال: key: (vars) => `...`.
// ============================================================

export const strings = {
  // ==========================================================
  // نصوص مشتركة تتكرر في أكثر من مكان
  // ==========================================================
  common: {
    appName: "روضة الاتحاد الحديثة",
    dashboard: "لوحة التحكم",
    children: "الأطفال",
    parents: "أولياء الأمور",
    teachers: "المعلمون",
    classes: "الصفوف",
    subjects: "المواد",
    sessions: "الحصص",
    attendance: "الحضور",
    notes: "الملاحظات",
    messages: "الرسائل",
    registrationRequests: "طلبات التسجيل",
    reports: "التقارير",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    close: "إغلاق",
    cancel: "إلغاء",
    save: "حفظ",
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    deleteConfirm: "حذف",
    statusActive: "نشط",
    statusSuspended: "موقوف",
    search: "بحث",
    notSpecified: "غير محدد",
    fallbackInitial: "؟",
    tableHeaderStatus: "الحالة",
    tableHeaderActions: "إجراءات",
    tableHeaderName: "الاسم",
    tableHeaderContact: "رقم التواصل",
    viewDetails: "عرض التفاصيل",
    noSearchResults: "لا يوجد نتائج مطابقة للبحث",
  },

  // ==========================================================
  // شاشة تسجيل الدخول
  // ==========================================================
  login: {
    roleAdmin: "مدير/ة",
    roleSecretary: "سكرتير/ة",
    roleTeacher: "معلم/ة",
    roleParent: "ولي أمر",
    missingCredentialsError: "الرجاء إدخال البريد الإلكتروني وكلمة المرور",
    appSubtitle: "نظام إدارة الروضة",
    loginAsLabel: "الدخول كـ",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "example@email.com",
    passwordLabel: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    passwordPlaceholder: "••••••••",
    showPasswordAria: "إظهار كلمة المرور",
    hidePasswordAria: "إخفاء كلمة المرور",
    rememberMe: "تذكرني على هذا الجهاز",
    loginLoading: "جارٍ تسجيل الدخول...",
    loginButton: "تسجيل الدخول",
    firstTimeMessage: "أول مرة تستخدم النظام؟",
    newParentCta: "ولي أمر جديد؟ قدّم طلب تسجيل طفل",
    loginHelp: "واجهت مشكلة بتسجيل الدخول؟",
    contactAdmin: "تواصلوا مع إدارة الروضة",
  },

  // ==========================================================
  // Sidebar & Navbar
  // ==========================================================
  sidebar: {
    adminPanelFallback: "لوحة الإدارة",
    sessionsSchedule: "الجدول والحصص",
    attendanceAbsence: "الحضور والغياب",
    myClassStudents: "طلاب صفي",
    mySchedule: "جدولي",
    myChildFile: "ملف طفلي",
    attendanceLog: "سجل الحضور",
    rateTeacher: "تقييم المعلم",
    quickSearchPlaceholder: "بحث سريع...",
    notificationsTitle: "الإشعارات",
    noNotifications: "لا يوجد إشعارات جديدة",
  },

  // ==========================================================
  // مكونات عامة
  // ==========================================================
  toast: {
    closeNotificationAria: "إغلاق التنبيه",
  },

  confirmModal: {
    confirmDeleteDefault: "حذف",
    cancelDefault: "إلغاء",
  },

  detailsModal: {
    unknownInitials: "؟",
    notSpecified: "غير محدد",
  },

  errorBoundary: {
    errorIcon: "⚠️",
    errorTitle: "عذراً، حدث خطأ ما",
    errorMessage: "حدث خطأ غير متوقع أثناء عرض الصفحة. يمكنك إعادة المحاولة أو تحديث الصفحة لمواصلة العمل.",
    errorDetails: "تفاصيل الخطأ",
    retryButton: "إعادة المحاولة",
    reloadButton: "تحديث الصفحة",
  },

  comingSoon: {
    fallbackPageTitle: "الصفحة",
    underConstruction: (title) => `صفحة ${title} قيد الإنشاء`,
    soonReady: "ستكون جاهزة قريباً",
  },

  // ==========================================================
  // لوحة التحكم
  // ==========================================================
  dashboard: {
    teacherPageBadge: "لوحة المعلمة",
    secretarySubtitle: "إليك ملخص الأعمال التي تحتاج متابعة اليوم.",

    // رأس المعلمة
    teacherWelcome: (name) => `صباح الخير، ${name}`,
    teacherGreeting: (classroom) => `أهلاً بكِ في يوم جديد مع أطفال ${classroom} 💚`,
    teacherGreetingFallbackClassroom: "صفك",
    teacherMotivationQuote: "\u201Cكل يوم فرصة جديدة لزرع فكرة جميلة في قلب طفل. ✨\u201D",
    teacherStatMyClassChildren: "أطفال صفي",
    teacherStatActiveChildren: "أطفال نشطون",
    teacherStatUnreadMessages: "رسائل غير مقروءة",
    teacherQuickActionsTitle: "اختصارات سريعة",
    teacherQuickActionsSubtitle: "أهم الأشياء التي قد تحتاجينها اليوم",
    teacherQuickActionAttendance: "تسجيل الحضور",
    teacherQuickActionAttendanceHint: "سجلي حضور أطفال صفك اليوم",
    teacherQuickActionAddNote: "إضافة ملاحظة",
    teacherQuickActionAddNoteHint: "سجلي ملاحظة عن أحد الأطفال",
    teacherQuickActionParentMessages: "رسائل الأهالي",
    teacherUnreadMessagesSummary: (n) =>
      n === 1
        ? `لديك ${n} رسالة تحتاج إلى متابعة`
        : `لديك ${n} رسائل تحتاج إلى متابعة`,
    teacherNoUnreadMessages: "لا توجد رسائل تحتاج متابعة",
    teacherStudentsCardTitle: "🌼 أطفال صفي",
    teacherNoStudents: "لا يوجد طلاب مسجلين بصفك بعد",
    teacherStudentsListTitle: (classroom) => `قائمة أطفال ${classroom}`,
    teacherActiveCountBadge: (n) =>
      n === 1 ? `${n} نشط` : `${n} نشطون`,
    teacherMessagesCardTitle: "💌 آخر رسائل الأهالي",
    teacherNoMessages: "صندوق الرسائل هادئ حالياً 🌿",
    teacherOpenAllMessages: "فتح كل الرسائل ←",

    // رأس السكرتيرة
    secretaryWelcome: (name) => `صباح الخير، ${name} 🌷`,
    secretaryStatActiveChildren: "الأطفال النشطون",
    secretaryStatParents: "أولياء الأمور",
    secretaryStatTeachers: "المعلمون",
    secretaryStatMessagesFollowUp: "رسائل تحتاج متابعة",
    secretaryQuickActionManageChildren: "إدارة الأطفال",
    secretaryQuickActionAttendance: "متابعة الحضور",
    secretaryQuickActionSchedules: "جدول الحصص",
    secretaryQuickActionMessages: "الرسائل",
    secretaryAlertTitle: "أطفال يحتاجون متابعة",
    secretaryAlertBody: (n) =>
      `يوجد ${n} ${n === 1 ? "طفل تجاوز" : "أطفال تجاوزوا"} 3 أيام غياب ويحتاج${n === 1 ? "" : "ون"} إلى مراجعة ولي الأمر.`,
    secretaryReviewAbsences: "مراجعة الغيابات ←",
    secretaryClassesCardTitle: "🏫 حالة الصفوف",
    secretaryNoClasses: "لا توجد صفوف مسجلة بعد.",
    secretaryClassNearCapacity: "الصف قريب من الطاقة الاستيعابية.",
    secretaryFollowUpCardTitle: "📌 يحتاج متابعة",
    secretaryFollowUpUnreadMessages: "رسائل غير مقروءة",
    secretaryFollowUpUnreadMessagesHint: "رسائل تحتاج إلى مراجعة",
    secretaryFollowUpAbsences: "غيابات تحتاج متابعة",
    secretaryFollowUpAbsencesHint: "أكثر من 3 أيام غياب",
    secretaryOpenReports: "فتح التقارير ←",

    // رأس المدير
    adminStatTotalChildren: "إجمالي الأطفال",
    adminStatActiveChildren: "الأطفال النشطون",
    adminStatTeachersCount: "عدد المعلمين",
    adminStatParents: "أولياء الأمور",
    adminQuickActionAttendanceToday: "تسجيل حضور اليوم",
    adminQuickActionAddChild: "إضافة طفل",
    adminQuickActionAddNote: "إضافة ملاحظة",
    adminClassDistributionTitle: "توزيع الأطفال حسب الصفوف",
    adminNoClasses: "لا يوجد صفوف مسجلة بعد",
    adminTodayAbsencesTitle: "غيابات اليوم",
    adminTodayAbsencesHint: "ستُعرض هنا تلقائياً بمجرد تسجيل الحضور اليومي",
    adminGoToAttendance: "الذهاب لتسجيل الحضور ←",
    adminLatestNotesTitle: "آخر الملاحظات",
    adminViewAllNotes: "عرض كل الملاحظات ←",
    adminRecentActivityTitle: "آخر الأنشطة",

    // أنشطة وهمية مؤقتة
    recentActivityAbsenceRecorded: "تم تسجيل غياب لـ رهف يوسف (صف الفراشات)",
    recentActivityTime20Minutes: "قبل 20 دقيقة",
    recentActivityNoteAdded: "أضافت المعلمة نور ملاحظة جديدة لـ يزن الأحمد",
    recentActivityTime1Hour: "قبل ساعة",
    recentActivityChildAdded: "تم إضافة طفل جديد: سيلين خالد (صف النجوم)",
    recentActivityTimeToday915: "اليوم، 9:15 ص",
    recentActivityParentUpdated: "تحديث بيانات ولي الأمر: أ. محمد درويش",
    recentActivityTimeYesterday: "أمس",
  },

  // ==========================================================
  // الأطفال
  // ==========================================================
  children: {
    pageTitle: "الأطفال",
    toggleStatusTitle: "اضغط لتبديل الحالة",
    searchPlaceholder: "ابحث باسم الطفل أو الصف...",
    addChildButton: "إضافة طفل",
    tableName: "الاسم",
    tableClassroom: "الصف",
    tableAge: "العمر",
    tableParent: "ولي الأمر",
    tableStatus: "الحالة",
    tableActions: "إجراءات",
    noResults: "لا يوجد نتائج مطابقة للبحث",
    confirmDeleteTitle: "تأكيد حذف الطفل",
    confirmDeleteMessage: "هل أنت متأكد من حذف هذا الطفل؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteButton: "حذف",
  },

  childForm: {
    ageFormatMonths: (v) => `${v} أشهر`,
    ageFormatYears: (v) => `${v} سنوات`,
    ageFormatYearsMonths: (v) => `${v.years} سنوات و${v.months} أشهر`,
    ageErrorTooYoung: (v) => `عمر الطفل أقل من الحد القانوني للقبول (3 سنوات و8 أشهر). العمر الحالي: ${v}`,
    ageErrorTooOld: (v) => `عمر الطفل أكبر من الحد القانوني للقبول (5 سنوات). العمر الحالي: ${v}`,
    modalTitleEdit: "تعديل بيانات الطفل",
    modalTitleAdd: "إضافة طفل جديد",
    fieldNameLabel: "اسم الطفل",
    fieldClassroomLabel: "الصف",
    fieldBirthDateLabel: "تاريخ الميلاد",
    currentAgeHint: (v) => `العمر الحالي: ${v}`,
    legalAgeHint: "العمر المقبول قانونياً: من 3 سنوات و8 أشهر إلى 5 سنوات",
    fieldParentLabel: "اسم ولي الأمر",
    cancelButton: "إلغاء",
    saveButton: "حفظ التعديلات",
    addButton: "إضافة",
  },

  childDetails: {
    pageTitle: "تفاصيل الطفل",
    behaviorPositive: "إيجابي",
    behaviorAlert: "تنبيه",
    attendanceSummaryTitle: "ملخص الحضور",
    attendanceLastDays: (v) => `آخر ${v} أيام`,
    attendancePercentage: (v) => `${v}%`,
    attendancePresentCount: (v) => `حاضر ${v}`,
    attendanceAbsentCount: (v) => `غائب ${v}`,
    noChildSelected: "لم يتم اختيار طفل. الرجاء الرجوع لقائمة الأطفال.",
    noteAuthorFallback: "مستخدم",
    backButton: "العودة إلى الأطفال",
    avatarFallback: "؟",
    heroStatusFallback: "غير محدد",
    heroClassroomFallback: "الصف غير محدد",
    heroSubtitle: "ملف الطفل والمتابعة اليومية",
    infoCardTitle: "معلومات الطفل",
    infoCardSubtitle: "البيانات الأساسية المسجلة",
    infoAgeLabel: "العمر",
    infoAgeValue: (v) => `${v} سنوات`,
    infoParentLabel: "ولي الأمر",
    infoPhoneLabel: "رقم التواصل",
    infoStatusLabel: "الحالة",
    healthNotesTitle: "ملاحظات صحية",
    tabBehaviors: "السلوكيات والملاحظات",
    tabAttendance: "سجل الحضور",
    behaviorsTitle: "السلوكيات والملاحظات",
    behaviorsSubtitle: "سجّلي اللحظات المهمة في رحلة الطفل",
    addNoteButton: "إضافة ملاحظة",
    noNotes: "لا توجد ملاحظات بعد",
    noNotesHint: "أضيفي أول ملاحظة لمتابعة تطور الطفل",
    noteFromSession: (v) => `من حصة: ${v}`,
    attendanceTitle: "سجل الحضور",
    attendanceSubtitle: "متابعة حضور وغياب الطفل",
    noteDefaultType: "إيجابي",
  },

  myChild: {
    pageTitle: "ملف طفلي",
    noChildTitle: "لا يوجد طفل مرتبط بحسابك",
    noChildMessage: "تواصلي مع إدارة الروضة لإضافة بيانات طفلك إلى حسابك.",
    familyPortalBadge: "أهلاً بك في بوابة العائلة",
    welcomeMessage: (v) => `أهلاً، ${v} 🌷`,
    welcomeSubtitle: "من هنا يمكنك متابعة أخبار أطفالك وحضورهم بسهولة.",
    childProfileLabel: "ملف الطفل",
    ageLabel: "العمر",
    ageValue: (v) => `${v} سنوات`,
    absencesLabel: "الغيابات",
    absencesValue: (v) => `${v} أيام`,
    teacherLabel: "معلمة الصف",
    teacherFallback: "غير محددة",
    callTeacherTitle: "الاتصال بالمعلمة",
    caregiverNote: "متابعة طفلك أولاً بأول تجعل تجربته في الروضة أجمل.",
    attendanceButton: "سجل الحضور",
    contactTeacherButton: "تواصل مع المعلمة",
    viewFullProfile: "عرض الملف الكامل",
    footerTitle: "نحن معك في كل خطوة",
    footerMessage: "يمكنك التواصل مع معلمة طفلك أو إدارة الروضة من قسم الرسائل.",
  },

  // ==========================================================
  // أولياء الأمور
  // ==========================================================
  parents: {
    statusToggleTitle: "اضغط لتبديل الحالة",
    parentRole: "ولي أمر",
    pageTitle: "أولياء الأمور",
    introText: "إدارة بيانات أولياء الأمور ومتابعة التواصل معهم",
    statsTotalLabel: "إجمالي أولياء الأمور",
    statsActiveLabel: "أولياء الأمور النشطون",
    searchPlaceholder: "ابحث باسم ولي الأمر أو الطفل...",
    addButton: "إضافة ولي أمر",
    detailPhoneLabel: "رقم الهاتف",
    detailPhoneFallback: "غير محدد",
    detailEmailLabel: "البريد الإلكتروني",
    detailEmailFallback: "غير محدد",
    detailChildrenLabel: "الأبناء",
    detailChildrenFallback: "غير محدد",
    detailStatusLabel: "الحالة",
    detailCloseButton: "إغلاق",
    rowAvatarFallback: "؟",
    confirmDeleteTitle: "تأكيد حذف ولي الأمر",
    confirmDeleteMessage: "هل أنت متأكد من حذف هذا ولي الأمر؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteLabel: "حذف",
  },

  parentForm: {
    headerEditTitle: "تعديل بيانات ولي الأمر",
    headerAddTitle: "إضافة ولي أمر جديد",
    headerEditSubtitle: "حدّثي البيانات ثم احفظي التغييرات",
    headerAddSubtitle: "أضيفي بيانات ولي الأمر إلى النظام",
    previewLabel: "معاينة ولي الأمر",
    previewNameFallback: "اسم ولي الأمر",
    previewPhoneFallback: "رقم التواصل",
    previewChildrenFallback: "الأبناء",
    labelFullName: "الاسم الكامل",
    namePlaceholder: "مثال: محمد أحمد",
    labelPhone: "رقم الهاتف",
    labelEmail: "البريد الإلكتروني",
    labelChildren: "اسم الطفل / الأبناء",
    childrenPlaceholder: "مثال: رهف يوسف",
    cancelButton: "إلغاء",
    submitEditLabel: "حفظ التعديلات",
    submitAddLabel: "إضافة ولي الأمر",
  },

  // ==========================================================
  // المعلمون
  // ==========================================================
  teachers: {
    statusToggleTitle: "اضغط لتبديل الحالة",
    pageTitle: "المعلمون",
    searchPlaceholder: "ابحث باسم المعلم، المادة أو الصف...",
    addButton: "إضافة معلم",
    tableHeaderTeacher: "المعلم",
    tableHeaderSubjects: "المواد",
    tableHeaderClassrooms: "الصفوف",
    tableHeaderWeeklyLessons: "الحصص الأسبوعية",
    tableHeaderStatus: "الحالة",
    tableHeaderActions: "إجراءات",
    initialsFallback: "م",
    weeklyLessonsSuffix: (v) => `${v} حصة`,
    emptyResult: "لا يوجد معلمون مطابقون للبحث",
    detailsSubtitle: "معلم/ة",
    detailsInitialsFallback: "م",
    detailsFieldSubjectsLabel: "المواد التي يدرّسها",
    detailsValueFallback: "غير محدد",
    detailsFieldClassroomsLabel: "الصفوف",
    detailsFieldPhoneLabel: "رقم الهاتف",
    detailsFieldWeeklyLessonsLabel: "الحصص الأسبوعية",
    detailsWeeklyLessonsValue: (v) => `${v} حصة`,
    detailsFieldStatusLabel: "الحالة",
    confirmDeleteTitle: "تأكيد حذف المعلم",
    confirmDeleteMessage: "هل أنت متأكد من حذف هذا المعلم/ة؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteLabel: "حذف",
  },

  teacherForm: {
    headerEditTitle: "تعديل بيانات المعلم",
    headerAddTitle: "إضافة معلم جديد",
    headerEditSubtitle: "حدّث بيانات المعلم والمواد والصفوف المسندة إليه",
    headerAddSubtitle: "أدخل بيانات المعلم وتوزيعه داخل الروضة",
    labelFullName: "الاسم الكامل",
    namePlaceholder: "مثال: نور أحمد",
    labelPhone: "رقم الهاتف",
    labelSubjects: "المواد التي يدرّسها",
    subjectsPlaceholder: "مثال: الرياضيات، اللغة العربية",
    subjectsHint: "يمكنك إدخال أكثر من مادة وفصل بينها بفاصلة",
    labelClassrooms: "الصفوف التي يدرّسها",
    classroomsPlaceholder: "مثال: الفراشات، النجوم",
    classroomsHint: "الصفوف التي تم إسناد حصص لهذا المعلم فيها",
    labelWeeklyLessons: "عدد الحصص الأسبوعية",
    weeklyLessonsPlaceholder: "مثال: 8",
    weeklyLessonsHint: "إجمالي الحصص المسندة للمعلم خلال الأسبوع",
    cancelButton: "إلغاء",
    submitEditLabel: "حفظ التعديلات",
    submitAddLabel: "إضافة المعلم",
  },

  // ==========================================================
  // الصفوف
  // ==========================================================
  classes: {
    capacityBadgeAvailable: "متاح",
    capacityBadgeFull: "ممتلئ",
    capacityBadgeAlmostFull: "قارب على الامتلاء",
    capacityCount: (v) => `${v.current} / ${v.capacity} طفل`,
    deleteBlockedWarning: (v) => `لا يمكن حذف "${v}" لأنه يحتوي على أطفال نشطين حالياً.`,
    pageTitle: "الصفوف",
    searchPlaceholder: "ابحث باسم الصف أو المعلم...",
    addClassButton: "إضافة صف",
    totalClassesLabel: "إجمالي الصفوف",
    registeredChildrenLabel: "الأطفال المسجلون",
    availableSeatsSummaryLabel: "المقاعد المتاحة",
    seatsAvailable: (v) => `${v} مقعد متاح`,
    noSeats: "لا توجد مقاعد",
    noClassesFound: "لا يوجد صفوف مطابقة للبحث",
    teacherDetail: (v) => `المعلمة: ${v}`,
    closeButton: "إغلاق",
    childrenDetailLabel: "الأطفال",
    capacityDetailLabel: "السعة",
    availableSeatsDetailLabel: "مقاعد متاحة",
    classChildrenTitle: "أطفال الصف",
    childAge: (v) => `العمر: ${v} سنوات`,
    noChildrenInClass: "لا يوجد أطفال مسجلون في هذا الصف",
    confirmDeleteTitle: "تأكيد حذف الصف",
    confirmDeleteMessage: (v) => `هل أنت متأكد من حذف الصف "${v}"؟ لا يمكن التراجع عن هذا الإجراء.`,
    confirmDeleteLabel: "حذف",
    viewClassDetailsTitle: "عرض تفاصيل الصف",
    editClassTitle: "تعديل الصف",
    deleteClassTitle: "حذف الصف",
  },

  classForm: {
    title: (v) => (v === "edit" ? "تعديل بيانات الصف" : "إضافة صف جديد"),
    subtitle: (v) =>
      v === "edit"
        ? "حدّثي بيانات الصف ثم احفظي التغييرات"
        : "أضيفي صفًا جديدًا إلى فصول الروضة",
    previewTitle: "معاينة الصف",
    previewClassNameFallback: "اسم الصف",
    previewTeacherFallback: "المعلمة المسؤولة",
    previewCapacityValue: (v) => `${v} طفل`,
    previewCapacityFallback: "السعة القصوى",
    labelClassName: "اسم الصف",
    classNamePlaceholder: "مثال: صف الفراشات",
    labelTeacher: "المعلمة المسؤولة",
    teacherPlaceholder: "مثال: أ. سارة الحاج",
    labelCapacityMax: "السعة القصوى",
    capacityPlaceholder: "مثال: 20",
    cancelButton: "إلغاء",
    submitButton: (v) => (v === "edit" ? "حفظ التعديلات" : "إنشاء الصف"),
  },

  // ==========================================================
  // المواد
  // ==========================================================
  subjects: {
    pageTitle: "المواد",
    headerTitle: "المواد التعليمية",
    headerDescription: "إدارة المواد والأنشطة التعليمية في الروضة",
    subjectsCount: (v) => `${v} مواد`,
    searchPlaceholder: "ابحث باسم المادة...",
    addSubjectButton: "إضافة مادة",
    teachersCount: (v) =>
      `${v} ${v === 1 ? "معلم" : v === 2 ? "معلمان" : "معلمين"}`,
    noResultsFound: "لا يوجد نتائج مطابقة للبحث",
    confirmDeleteTitle: "تأكيد حذف المادة",
    confirmDeleteMessage: "هل أنت متأكد من حذف هذه المادة؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteLabel: "حذف",
  },

  subjectForm: {
    title: (v) => (v === "edit" ? "تعديل المادة" : "إضافة مادة جديدة"),
    subtitle: "حددي المادة وعدد حصصها والمعلمات وجدولها الأسبوعي",
    sectionBasicInfo: "معلومات المادة",
    labelSubjectName: "اسم المادة",
    subjectNamePlaceholder: "مثال: الرياضيات",
    labelWeeklyClasses: "عدد الحصص أسبوعيًا",
    sectionTeachers: "المعلمات المسؤولات",
    teacherSelectedBadge: "محددة",
    sectionWeeklySchedule: "جدول الحصص الأسبوعي",
    addClassToScheduleButton: "إضافة حصة للجدول",
    scheduleItemDetail: (v) => `${v.from} - ${v.to} · ${v.teacher}`,
    cancelButton: "إلغاء",
    submitButton: (v) => (v === "edit" ? "حفظ التعديلات" : "إضافة المادة"),
  },

  // ==========================================================
  // الحصص
  // ==========================================================
  sessions: {
    days: {
      sunday: "الأحد",
      monday: "الاثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
    },
    subjectPatterns: {
      arabic: "عربية",
      math: "رياضيات",
      art: "فنية",
      motor: "حركي",
    },
    toast: {
      selectChildFirst: "يرجى اختيار الطفل أولاً قبل إضافة الملاحظة.",
      childNotInClass: "هذا الطفل ليس ضمن صفك.",
      noteOnlyForOwnClass: "لا يمكنك إضافة ملاحظة إلا لأطفال صفك.",
    },
    pageTitle: "الحصص",
    header: {
      roleBadgeTeacher: "عرض الجدول",
      roleBadgeManager: "إدارة الجدول",
      title: "الجدول الدراسي",
      teacherSubtitle: "اطلعي على جدول الحصص وتابعي حصصك وملاحظاتك.",
      adminSubtitle: "نظرة سريعة على حصص اليوم والجدول الأسبوعي.",
      addButton: "إضافة حصة",
    },
    teacherInfoCard: {
      title: "جدول الروضة",
      description: "يمكنك مشاهدة حصص جميع الصفوف، لكن يمكنك توثيق وإضافة ملاحظات فقط على الحصص التي تقومين بتدريسها.",
    },
    dayHeader: {
      daySessionsTitle: (v) => `حصص يوم ${v}`,
      noSessions: "لا توجد حصص مجدولة",
      sessionsCount: (n) => `${n} ${n === 1 ? "حصة" : "حصص"} اليوم`,
      teacherOnlyHint: "التوثيق متاح لحصصك فقط",
      emptyStateTitle: "يوم هادئ 🌿",
      emptyStateSubtitle: "لا توجد حصص مجدولة لهذا اليوم",
    },
    sessionCard: {
      completedBadge: "تمت الحصة ✓",
      classroomPrefix: (v) => `🏫 ${v}`,
      teacherPrefix: (v) => `👩🏫 ${v}`,
      markCompletedButton: "تم تنفيذ الحصة",
      noteButtonEdit: "تعديل الملاحظات",
      noteButtonAdd: "إضافة ملاحظة",
      lessonNoteHeading: "ملاحظة عن الحصة",
      editButton: "تعديل",
      deleteButton: "حذف",
    },
    noteTypeModal: {
      title: "إضافة ملاحظة",
      subjectClassSubtitle: (subject, classroom) => `${subject} — ${classroom}`,
      lessonNoteOption: "ملاحظة عن الحصة",
      lessonNoteDesc: "اكتبي ملاحظة عامة عن سير الحصة وتفاعل الأطفال.",
      childNoteOption: "ملاحظة عن طفل",
      childNoteDesc: "اختاري طفلًا من صفك ثم أضيفي الملاحظة في صفحة الملاحظات.",
    },
    lessonNoteModal: {
      title: "ملاحظة عن الحصة",
      label: "ملاحظات المعلمة عن الحصة",
      placeholder: "مثال: كان تفاعل الأطفال ممتازًا اليوم، وتم تنفيذ النشاط بشكل جيد...",
      hint: "هذه الملاحظة تخص الحصة كاملة وليست ملاحظة لطفل معين.",
      cancelButton: "إلغاء",
      saveButton: "حفظ الملاحظة",
      fallbackUserName: "مستخدم",
    },
    childSelector: {
      title: "ملاحظة عن طفل",
      label: "اختاري الطفل",
      emptyMessage: "لا يوجد أطفال مسجلون في صفك حاليًا.",
      placeholderOption: "اختاري الطفل...",
      hint: "يظهر هنا فقط أطفال صفك، ولا يمكنك إضافة ملاحظة لطفل من صف آخر.",
      cancelButton: "إلغاء",
      continueButton: "متابعة",
    },
    deleteConfirm: {
      title: "تأكيد حذف الحصة",
      message: "هل أنت متأكد من حذف هذه الحصة؟ لا يمكن التراجع عن هذا الإجراء.",
      confirmLabel: "حذف",
    },
  },

  sessionForm: {
    headerTitleEdit: "تعديل الحصة",
    headerTitleAdd: "إضافة حصة جديدة",
    headerSubtitle: "رتّبي وقت الحصة وبياناتها بسهولة",
    previewLabel: "معاينة الحصة",
    previewSubjectFallback: "اسم المادة",
    previewTimeFallback: "وقت الحصة",
    previewClassroomFallback: "الصف",
    previewTeacherFallback: "المعلم",
    labelDay: "اليوم",
    labelTime: "الوقت",
    labelSubject: "المادة",
    labelClassroom: "الصف",
    labelTeacher: "المعلم",
    placeholderTime: "مثال: 9:00 - 9:45",
    placeholderSubject: "مثال: اللغة العربية",
    placeholderClassroom: "مثال: صف الفراشات",
    placeholderTeacher: "مثال: أ. سارة الحاج",
    cancelButton: "إلغاء",
    submitEdit: "حفظ التعديلات",
    submitAdd: "إضافة الحصة",
  },

  // ==========================================================
  // الحضور
  // ==========================================================
  attendance: {
    statusPresent: "حاضر",
    statusAbsent: "غائب",
    statusLate: "متأخر",
    teacherStatusPresent: "حاضرة",
    teacherStatusAbsent: "غائبة",
    teacherStatusLate: "متأخرة",
    emptyChildrenTitle: "الحضور",
    emptyChildrenMessage: "لا يوجد أطفال مسجلين ببياناتك حاليًا.",
    pageTitleDefault: "الحضور",
    pageTitleParent: "سجل حضور أطفالي",
    headerSubtitleParent: "يمكنك متابعة حضور أطفالك وسجل الغياب",
    headerSubtitleTeacher: (v) => `تسجيل حضور ${v}`,
    headerSubtitleSecretary: "متابعة حضور الأطفال والمعلمات",
    headerSubtitleAdmin: "إدارة ومتابعة حضور أطفال الروضة",
    todayAbsenceCountLabel: "غياب اليوم",
    teacherSectionTitle: "حضور المعلمة",
    teacherSectionSubtitle: "تسجيل ومتابعة حضور المعلمات لهذا اليوم",
    saveTeacherAttendanceBtn: "حفظ حضور المعلمة",
    teacherSavedMessage: "تم حفظ الحضور",
    noTeachersRegistered: "لا توجد معلمات مسجلات.",
    teacherStatusNotRecorded: "لم يسجل",
    parentNoticeTitle: "سجل الحضور للمتابعة فقط",
    parentNoticeBody: "يمكنك الاطلاع على حضور طفلك وغياباته، بينما تسجيل الحضور من صلاحية المعلمة وإدارة الروضة.",
    alertTitle: "متابعة غياب مطلوبة",
    alertBody: "تم تجاوز 3 غيابات. يُنصح بالتواصل مع ولي الأمر لمتابعة السبب.",
    alertAbsenceCount: (v) => `${v} غيابات — يحتاج متابعة`,
    alertContactBtn: "التواصل مع ولي الأمر",
    alertParentLabel: "ولي الأمر:",
    childrenSavedMessage: "تم حفظ الحضور",
    saveChildrenAttendanceBtn: "حفظ حضور الأطفال",
    absenceBadge: (v) => `${v} غياب`,
    lastRecordLabel: (v) => `آخر تسجيل: ${v ?? "لا يوجد"}`,
    lastRecordNone: "لا يوجد",
    latestStatusPresent: "حاضر",
    latestStatusLate: "متأخر",
    latestStatusExcused: "غائب بعذر",
    latestStatusUnexcused: "غائب بدون عذر",
    noRecordMessage: "لا يوجد تسجيل",
    excuseLabel: "سبب الغياب / العذر",
    excusePlaceholder: "مثال: مرض، موعد طبي، ظرف عائلي...",
    excuseHint: "كتابة العذر تسجل الغياب \"بعذر\"، وتركه فارغًا يسجل الغياب \"بدون عذر\".",
    parentRoleFallback: "ولي الأمر",
    teacherRoleFallback: "معلمة",
  },

  // ==========================================================
  // الملاحظات
  // ==========================================================
  notes: {
    typePositive: "إيجابي",
    typeNormal: "ملاحظة",
    typeAlert: "تنبيه",
    defaultUserName: "مستخدم",
    pageTitle: "الملاحظات",
    headerTitle: "ملاحظات الأطفال",
    headerSubtitle: "تابعي ملاحظات الأطفال وسلوكهم وتطورهم اليومي",
    addButton: "إضافة ملاحظة",
    statTotal: "إجمالي الملاحظات",
    statPositive: "ملاحظات إيجابية",
    statAlerts: "تنبيهات",
    searchPlaceholder: "ابحث باسم الطفل أو نص الملاحظة...",
    editTitleAttr: "تعديل",
    deleteTitleAttr: "حذف",
    emptyTitle: "لا توجد ملاحظات مطابقة",
    emptyHint: "جرّبي البحث باسم طفل آخر أو كلمة مختلفة",
    deleteModalTitle: "تأكيد حذف الملاحظة",
    deleteModalMessage: "هل أنت متأكد من حذف هذه الملاحظة؟ لا يمكن التراجع عن هذا الإجراء.",
    deleteModalConfirm: "حذف",
  },

  noteForm: {
    formTypes: ["إيجابي", "ملاحظة", "تنبيه"],
    titleEdit: "تعديل ملاحظة الطفل",
    titleAdd: "إضافة ملاحظة عن طفل",
    fieldChild: "اسم الطفل",
    noChildren: "لا يوجد أطفال مسجلين بعد. أضيفي طفل أول من صفحة الأطفال.",
    fieldType: "نوع الملاحظة",
    fieldText: "نص الملاحظة",
    textPlaceholder: "اكتبي ملاحظة عن الطفل...",
    cancel: "إلغاء",
    submitEdit: "حفظ التعديلات",
    submitAdd: "إضافة الملاحظة",
  },

  // ==========================================================
  // الرسائل
  // ==========================================================
  messages: {
    fallbackTeacher: "معلم الصف",
    fallbackParent: "ولي الأمر",
    sendNoticePending: (v) => `تم استلام رسالتك 🌿 سيتم إرسالها إلى ${v.teacherName} الساعة ${v.time} لأن وقت التواصل المحدد هو من 6:00 إلى 7:00 مساءً.`,
    sendNoticeParentSuccess: (v) => `تم إرسال رسالتك إلى ${v.teacherName} بنجاح ✓`,
    sendNoticeTeacherSuccess: (v) => `تم إرسال الرسالة إلى ${v.parentName} بنجاح ✓`,
    subtitleParentView: (v) => `معلم ${v.classroom || "الصف"}`,
    subtitleTeacherView: (v) => `ولي أمر ${v.childName}`,
    contactTimeLabel: "وقت التواصل مع المعلم:",
    contactTimeValue: "6:00 – 7:00 مساءً",
    bannerTeacherHint: "المحادثة مع ولي أمر الطفل",
    emptyTitle: "ابدئي المحادثة 🌿",
    emptyParentHint: "يمكنك التواصل مع معلم طفلك خلال وقت التواصل المحدد.",
    emptyTeacherHint: "يمكنك التواصل مع ولي أمر الطفل مباشرة.",
    announcementBadge: "إعلان عام",
    pendingBadge: "بانتظار وقت التواصل",
    inputParentPlaceholder: "اكتبي رسالتك للمعلم...",
    inputTeacherPlaceholder: "اكتب رسالة لولي الأمر...",
    sendTitleAttr: "إرسال الرسالة",
    announcementModalTitle: "إعلان عام لكل أهالي الصف",
    announcementModalDesc: "سيصل هذا الإعلان إلى جميع أولياء أمور طلاب صفك",
    announcementCountSingular: "ولي أمر",
    announcementCountPlural: "أولياء أمور",
    announcementPlaceholder: "اكتبي نص الإعلان...",
    announcementCancel: "إلغاء",
    announcementSend: "إرسال للجميع",
    pageTitle: "الرسائل",
    noThreads: "لا توجد محادثات بعد",
    announceAllButton: "إعلان عام لكل الصف",
    studentItemSubtitle: (v) => `ولي أمر ${v.childName}`,
    studentNoMessages: "لا توجد رسائل بعد",
  },

  // ==========================================================
  // طلبات التسجيل
  // ==========================================================
  registrationRequests: {
    statusPending: "بانتظار المراجعة",
    statusApproved: "تمت الموافقة",
    statusRejected: "مرفوض",
    childFallbackName: "طفل جديد",
    submittedOn: (v) => `قُدّم بتاريخ ${v}`,
    detailsTitle: "تفاصيل طلب التسجيل",
    childInfoSection: "👶 معلومات الطفل",
    childNameLabel: "اسم الطفل",
    genderLabel: "الجنس",
    birthDateLabel: "تاريخ الميلاد",
    parentInfoSection: "👨‍👩‍👧 معلومات ولي الأمر",
    fatherNameLabel: "اسم الأب",
    fatherPhoneLabel: "هاتف الأب",
    motherNameLabel: "اسم الأم",
    motherPhoneLabel: "هاتف الأم",
    parentsStatusLabel: "الوضع الحالي للوالدين",
    emergencyContactLabel: "وسيلة اتصال الطوارئ",
    healthConditionsTitle: "حالات أو معلومات صحية",
    specialNeedsTitle: "احتياجات خاصة",
    extraNotesTitle: "ملاحظات إضافية",
    rejectButton: "رفض الطلب",
    approveButton: "قبول وإضافة للروضة",
    approvedMessage: "تمت الموافقة على الطلب وإضافة الطفل إلى النظام.",
    rejectedMessage: "تم رفض طلب التسجيل.",
    classroomPendingAssignment: "بانتظار توزيع الصف",
    pageTitle: "طلبات التسجيل",
    welcomeEmoji: "🌷",
    newRegistrationsLabel: "تسجيلات جديدة",
    welcomeTitle: "طلبات الالتحاق بالروضة",
    welcomeDescription: "راجعي طلبات الأهالي قبل اعتماد تسجيل أطفالهم في الروضة. 💚",
    pendingStatLabel: (v) => (v === 1 ? "طلب يحتاج مراجعة" : "طلبات تحتاج مراجعة"),
    approvedStatLabel: (v) => (v === 1 ? "طلب تمت الموافقة عليه" : "طلبات تمت الموافقة عليها"),
    rejectedStatLabel: "طلب مرفوض",
    filterPending: "بانتظار المراجعة",
    filterApproved: "مقبولة",
    filterRejected: "مرفوضة",
    filterAll: "الكل",
    emptyStateTitle: "لا توجد طلبات هنا حاليًا",
    emptyStateDescription: "ستظهر طلبات الأهالي هنا عند إرسالها.",
    confirmRejectTitle: "رفض طلب التسجيل",
    confirmRejectMessage: "هل أنت متأكد من رفض هذا الطلب؟ يمكن للولي إعادة التقديم لاحقاً.",
    confirmRejectLabel: "رفض الطلب",
  },

  registrationForm: {
    stepChildData: "بيانات الطفل",
    stepHealthAndFamily: "الحالة الصحية والعائلية",
    stepBehaviorAndCommunication: "السلوكيات والتواصل",
    conditionDiabetes: "سكري أطفال",
    conditionEpilepsy: "صرع",
    conditionAllergy: "حساسية",
    conditionAsthma: "أزمة",
    conditionHeart: "القلب",
    conditionFungus: "فطريات",
    conditionChickenpox: "جدري",
    conditionLice: "تقمل",
    specialNeedMotor: "حركية",
    specialNeedHearing: "سمعية",
    specialNeedVisual: "بصرية",
    specialNeedSpeech: "نطقية",
    parentsStatusMarried: "متزوجين",
    parentsStatusDivorced: "مطلقين",
    parentsStatusSeparated: "منفصلين",
    parentsStatusOneDeceased: "أحدهما متوفى",
    yesOption: "نعم",
    noOption: "لا",
    submittedSuccessTitle: "تم إرسال طلب التسجيل بنجاح",
    submittedSuccessMessage: "شكرًا لتقديم طلب التسجيل في روضة الاتحاد الحديثة. ستقوم إدارة الروضة بمراجعة الطلب والتواصل معكم لتحديد موعد المقابلة واستكمال إجراءات التسجيل.",
    keepContactInfoMessage: "يرجى الاحتفاظ بمعلومات التواصل الخاصة بكم، حيث سيتم استخدامها من قبل إدارة الروضة للتواصل معكم بخصوص الطلب.",
    backToLoginButton: "رجوع لتسجيل الدخول",
    formTitle: "طلب تسجيل طفل جديد",
    formIntro: "يرجى تعبئة البيانات التالية لتقديم طلب التسجيل. بعد إرسال الطلب ستقوم إدارة الروضة بمراجعته والتواصل معكم لاستكمال إجراءات التسجيل.",
    sectionBasicChildData: "بيانات الطفل الأساسية",
    childFullNameLabel: "اسم الطفل الرباعي",
    childFullNamePlaceholder: "أدخل اسم الطفل الكامل",
    genderLabel: "الجنس",
    birthDateLabel: "تاريخ الميلاد",
    birthPlaceLabel: "مكان الولادة",
    birthPlacePlaceholder: "مثال: مستشفى النجاح",
    expectedEnrollDateLabel: "تاريخ دخول الروضة المتوقع",
    sectionAddressAndContact: "عنوان السكن والتواصل",
    currentAddressLabel: "عنوان السكن الحالي",
    currentAddressPlaceholder: "المدينة / المنطقة",
    homePhoneLabel: "هاتف البيت",
    homePhonePlaceholder: "059-XXXXXXX",
    siblingsCountLabel: "عدد الإخوة",
    childOrderLabel: "ترتيب الطفل في الأسرة",
    sectionFatherData: "بيانات الأب",
    fatherNameLabel: "اسم الأب",
    fatherJobLabel: "عمل الأب",
    workplaceLabel: "مكان العمل",
    fatherPhoneLabel: "جوال الأب",
    fatherPhonePlaceholder: "059-XXXXXXX",
    sectionMotherData: "بيانات الأم",
    motherNameLabel: "اسم الأم",
    motherJobLabel: "عمل الأم",
    motherPhoneLabel: "جوال الأم",
    motherPhonePlaceholder: "059-XXXXXXX",
    sectionParentsStatus: "الوضع الحالي للوالدين",
    sectionFamilyStatus: "الحالة العائلية",
    travelingParentQuestion: "هل أحد الوالدين مسافر؟",
    optionFather: "الأب",
    optionMother: "الأم",
    optionNone: "لا يوجد",
    deceasedParentQuestion: "هل أحد الوالدين متوفى؟",
    parentsRelationLabel: "صلة القرابة بين الوالدين",
    parentsRelationPlaceholder: "إن وجدت",
    sectionHealthStatus: "الحالة الصحية",
    healthConditionsQuestion: "هل يعاني الطفل من أي أمراض أو حالات صحية؟",
    otherConditionLabel: "حالة صحية أخرى",
    otherConditionPlaceholder: "اذكر أي حالة غير موجودة في القائمة",
    surgeryQuestion: "هل سبق وأجريت للطفل عملية؟",
    surgeryDetailsLabel: "تفاصيل العملية",
    surgeryDetailsPlaceholder: "اذكر نوع العملية وتاريخها إن أمكن",
    medicineQuestion: "هل يتناول الطفل أدوية حاليًا؟",
    medicineDetailsLabel: "تفاصيل الأدوية",
    medicineDetailsPlaceholder: "اسم الدواء أو الأدوية",
    vaccinationQuestion: "هل أخذ الطفل جميع التطعيمات اللازمة؟",
    sectionSpecialNeeds: "الاحتياجات الخاصة",
    specialNeedsQuestion: "هل لدى الطفل أي احتياجات خاصة؟",
    specialNeedsSupervisorLabel: "الجهة المشرفة على الحالة",
    specialNeedsSupervisorPlaceholder: "اسم المركز أو الجهة إن وجدت",
    familySpecialNeedsQuestion: "هل يوجد في الأسرة شخص من ذوي الاحتياجات الخاصة؟",
    countLabel: "العدد",
    conditionTypeLabel: "نوع الحالة",
    sectionBehaviorAndHabits: "سلوكيات وعادات الطفل",
    bedwettingQuestion: "هل يبلل فراشه؟",
    breakfastQuestion: "هل يتناول فطوره بانتظام؟",
    sleepQuestion: "هل ينام بشكل طبيعي؟",
    nervousQuestion: "هل يتصف بالعصبية؟",
    introvertShyQuestion: "هل يميل للانطواء أو الخجل؟",
    aggressiveQuestion: "هل تظهر عليه سلوكيات عدوانية؟",
    stutteringQuestion: "هل يعاني من التأتأة؟",
    sectionEmergencyContact: "وسيلة الاتصال في حالات الطوارئ",
    emergencyContactLabel: "اسم ورقم الشخص الذي يتم التواصل معه",
    emergencyContactPlaceholder: "الاسم - رقم الهاتف",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    prevStepButton: "السابق",
    nextStepButton: "التالي",
    submitButton: "إرسال طلب التسجيل",
    privacyNotice: "نود إعلامكم بأن المعلومات الواردة في هذه الاستمارة تستخدم لأغراض التسجيل والتواصل مع إدارة الروضة، وسيتم التعامل معها بسرية. ويتحمل ولي الأمر مسؤولية صحة البيانات المقدمة.",
  },

  // ==========================================================
  // التقارير
  // ==========================================================
  reports: {
    reportAttendance: "تقرير الحضور",
    reportAttendanceDesc: "متابعة حضور وغياب الأطفال",
    reportChildren: "تقرير الأطفال",
    reportChildrenDesc: "ملخص بيانات الأطفال المسجلين",
    reportBehavior: "تقرير السلوكيات",
    reportBehaviorDesc: "متابعة الملاحظات والسلوكيات",
    pageTitle: "التقارير",
    headerTitle: "التقارير والإحصائيات",
    headerDescription: "اختاري نوع التقرير والفترة الزمنية لعرض البيانات المطلوبة",
    reportTypeLabel: "نوع التقرير",
    filterTitle: "تصفية التقرير",
    filterDescription: "حددي البيانات التي تريدين ظهورها",
    classroomLabel: "الصف",
    fromDateLabel: "من تاريخ",
    toDateLabel: "إلى تاريخ",
    showReportButton: "عرض التقرير",
    exportPdfButton: "تصدير PDF",
    printButton: "طباعة",
    previewHintBefore: "حددي الفلاتر المطلوبة ثم اضغطي على",
    previewHintAction: "\"عرض التقرير\"",
    previewHintAfter: "لعرض النتائج هنا.",
  },

  // ==========================================================
  // تقييم المعلم
  // ==========================================================
  rating: {
    criterionInteraction: "التعامل مع الطفل",
    criterionCare: "الاهتمام والمتابعة",
    criterionCommunication: "التواصل مع ولي الأمر",
    criterionActivities: "الأنشطة والتعليم",
    starAriaLabel: (v) => `تقييم ${v} من 5`,
    pageTitle: "تقييم المعلم",
    parentsOnlyMessage: "هذه الصفحة متاحة لأولياء الأمور فقط",
    ratedTitleWithStar: "تقييم المعلم ⭐",
    shareExperienceHint: "شاركينا رأيك حول تجربة طفلك مع معلمه.",
    noTeacherMessage: "لا يوجد معلم مرتبط بطفلك حاليًا",
    noTeacherDescription: "سيتم عرض المعلم هنا عند ربط الطفل بصفه.",
    allAspectsWarning: "يرجى تقييم جميع الجوانب قبل إرسال التقييم.",
    submittedSuccessTitle: "تم إرسال تقييمك بنجاح 🌷",
    submittedSuccessMessage: "شكرًا لمساهمتك في تحسين تجربة أطفالنا.",
    backToChildProfileButton: "العودة إلى ملف طفلي",
    teacherClassChild: (teacherClass, childName) => `${teacherClass} · ${childName}`,
    alreadyRatedMessage: "تم إرسال تقييمك لهذا المعلم مسبقًا.",
    ratingForChild: (v) => `تقييم خاص بـ ${v}`,
    yourNoteLabel: "ملاحظتك",
    optionalLabel: "(اختياري)",
    notePlaceholder: "اكتبي أي ملاحظات أو اقتراحات...",
    submitRatingButton: "إرسال التقييم",
  },

  // ==========================================================
  // الملف الشخصي
  // ==========================================================
  profile: {
    initialFallback: "س",
    pageTitle: "الملف الشخصي",
    accountTypeLabel: "حساب المستخدم",
    editButton: "تعديل",
    emailLabel: "البريد الإلكتروني",
    phoneLabel: "رقم الهاتف",
    joinDateLabel: "تاريخ الانضمام",
    memberSince: (v) => `عضو منذ ${v}`,
    footerLabel: "معلومات الحساب الشخصية",
    editTitle: "تعديل معلومات الحساب",
    editDescription: "حدّثي البيانات ثم احفظي التغييرات",
    fullNameLabel: "الاسم الكامل",
    cancelButton: "إلغاء",
    saveButton: "حفظ التعديلات",
  },

  // ==========================================================
  // الإعدادات
  // ==========================================================
  settings: {
    pageTitle: "الإعدادات",
    systemSettingsTitle: "إعدادات النظام",
    introDescription: "تحكّمي بالتنبيهات والأمان واللغة بالطريقة التي تناسبك.",
    notificationsSectionTitle: "التنبيهات",
    notificationsSectionDesc: "اختاري التنبيهات التي تريدين استقبالها",
    inAppNotificationsLabel: "إشعارات داخل التطبيق",
    inAppNotificationsDesc: "تنبيهات الحضور والملاحظات الجديدة",
    smsAlertsLabel: "تنبيهات SMS",
    smsAlertsDesc: "إرسال رسائل نصية لأولياء الأمور عند الغياب",
    securitySectionTitle: "الأمان",
    securitySectionDesc: "حافظي على أمان حسابك",
    changePasswordLabel: "تغيير كلمة المرور",
    changePasswordDesc: "حدّثي كلمة المرور الخاصة بحسابك",
    languageSectionTitle: "اللغة",
    languageSectionDesc: "اختاري لغة واجهة النظام",
    systemLanguageLabel: "لغة النظام",
    languageArabic: "العربية",
    languageEnglish: "English",
  },

  // ==========================================================
  // رسائل الـ Contexts (أخطاء وحالات)
  // ==========================================================
  context: {
    children: {
      error403: "ليس لديك صلاحية للقيام بهذه العملية",
      error404: "السجل غير موجود",
      errorNetwork: "تعذّر الاتصال بالسيرفر، تحقق من الشبكة",
      fetchFailed: "فشل تحميل قائمة الأطفال",
      addSuccess: "تم إضافة الطفل بنجاح",
      addFailed: "فشل إضافة الطفل",
      addDemoSuccess: "تم إضافة الطفل (وضع تجريبي)",
      updateSuccess: "تم تحديث بيانات الطفل بنجاح",
      updateFailed: "فشل تعديل بيانات الطفل",
      updateDemoSuccess: "تم التحديث (وضع تجريبي)",
      deleteFailed: "فشل حذف الطفل من السيرفر",
      deleteSuccess: "تم حذف الطفل بنجاح",
    },
    registrationRequests: {
      error404: "الطلب غير موجود",
      fetchFailed: "فشل تحميل طلبات التسجيل",
      submitSuccess: "تم إرسال طلب التسجيل بنجاح",
      submitFailed: "فشل إرسال طلب التسجيل",
      submitDemoSuccess: "تم إرسال الطلب (وضع تجريبي)",
      statusApprovedLabel: "قبول",
      statusRejectedLabel: "رفض",
      statusUpdatedLabel: "تحديث",
      updateSuccess: (label) => `تم ${label} الطلب بنجاح`,
      updateFailed: "فشل تحديث حالة الطلب",
      updateDemoSuccess: "تم التحديث (وضع تجريبي)",
    },
    teachers: {
      fetchFailed: "فشل تحميل قائمة المعلمين",
      addSuccess: "تم إضافة المعلم بنجاح",
      addFailed: "فشل إضافة المعلم",
      addDemoSuccess: "تم إضافة المعلم (وضع تجريبي)",
      updateSuccess: "تم تحديث بيانات المعلم بنجاح",
      updateFailed: "فشل تعديل بيانات المعلم",
      updateDemoSuccess: "تم التحديث (وضع تجريبي)",
      deleteFailed: "فشل حذف المعلم من السيرفر",
      deleteSuccess: "تم حذف المعلم بنجاح",
    },
    parents: {
      fetchFailed: "فشل تحميل قائمة أولياء الأمور",
      addSuccess: "تم إضافة ولي الأمر بنجاح",
      addFailed: "فشل إضافة ولي الأمر",
      addDemoSuccess: "تم إضافة ولي الأمر (وضع تجريبي)",
      updateSuccess: "تم تحديث بيانات ولي الأمر بنجاح",
      updateFailed: "فشل تعديل بيانات ولي الأمر",
      updateDemoSuccess: "تم التحديث (وضع تجريبي)",
      deleteFailed: "فشل حذف ولي الأمر من السيرفر",
      deleteSuccess: "تم حذف ولي الأمر بنجاح",
    },
    attendance: {
      fetchFailed: "فشل تحميل سجلات الحضور",
      saveSuccess: "تم حفظ سجلات الحضور بنجاح",
      saveFailed: "فشل حفظ سجلات الحضور",
    },
    auth: {
      loginFailedFallback: "فشل تسجيل الدخول",
    },
    defaultAuthor: "مستخدم",
  },

  // ==========================================================
  // بيانات أولية وهمية (Seed Data)
  // ==========================================================
  seed: {
    days: {
      sunday: "الأحد",
      monday: "الاثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
    },
    subjects: {
      arabic: "اللغة العربية",
      math: "الرياضيات",
      art: "التربية الفنية",
      motor: "النشاط الحركي",
    },
    classes: {
      butterflies: "صف الفراشات",
      stars: "صف النجوم",
      moon: "صف القمر",
      sun: "صف الشمس",
    },
    teachers: {
      saraHajj: "أ. سارة الحاج",
      reemAwda: "أ. ريم عودة",
      noorSalama: "أ. نور سلامة",
      linaKhalil: "أ. لينا خليل",
      teacherSara: "المعلمة سارة",
      teacherNoor: "المعلمة نور",
      teacherReem: "المعلمة ريم",
      teacherLayan: "المعلمة ليان",
    },
    children: {
      rahafYoussef: "رهف يوسف",
      yazan: "يزن الأحمد",
      selin: "سيلين خالد",
      zain: "زين محمود",
      parentYoussef: "محمد يوسف",
      parentYazan: "علي الأحمد",
      parentSelin: "خالد درويش",
      parentZain: "محمود عودة",
    },
    timeSlots: {
      slot1: "9:00 - 9:45",
      slot2: "10:00 - 10:45",
    },
    demoAccounts: {
      adminName: "أ. سارة أحمد",
      adminRole: "مديرة الروضة",
      adminJoinDate: "أيلول 2022",
      secretaryName: "أ. ليان خالد",
      secretaryRole: "سكرتيرة المدير",
      secretaryJoinDate: "آذار 2024",
      teacherName: "أ. نور سلامة",
      teacherRole: "معلمة",
      teacherJoinDate: "شباط 2023",
      teacherClassroom: "صف الفراشات",
      parentName: "محمد يوسف",
      parentRole: "ولي أمر",
      parentJoinDate: "أيلول 2024",
    },
  },
};

export default strings;